### ISSUE TITLE
package.json main field is pointing an invalid path

### ISSUE THREAD

**Issue by ci010** [LanceMcCarthy/PartnerCenterBroker#9]
The main should be `dist/index.js`

**Comment by LanceMcCarthy** [comment]
This repo is a GitHub Action, not a website/app. Main is always `"main": "lib/main.js"` for TypeScript Actions.


For more information about GitHub Actions, visit https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16 or you can see the official template here https://github.com/actions/typescript-action
